// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "../node_modules/rescript/lib/es6/caml_option.js";

function testAlert(param) {
  param.alert("it work!");
  
}

function a(param) {
  return Caml_option.nullable_to_opt(param.getElementById("1"));
}

var DOM;

var Doc;

var Elem;

var HtmlElem;

var InputElem;

var EvtTarget;

export {
  DOM ,
  Doc ,
  Elem ,
  HtmlElem ,
  InputElem ,
  EvtTarget ,
  testAlert ,
  a ,
  
}
/* No side effect */
